swagger: "2.0"
info: 
  version: "0.0.1"
  title: "filter"
  description: "A simple service to pull OpenStack flavor"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Michael Robinson"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh/flavor"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /lavor:
    get: 
      description: "Returns flavor of OpenStack implementation"
      operationId: flavor
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Type of OpenStack flavor"
      parameters:
        - id: "string"

        
   
